# Generated by Django 4.1 on 2024-05-17 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="mainphoto",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
