# Generated by Django 4.1 on 2024-05-24 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_post_mainphoto"),
    ]

    operations = [
        migrations.CreateModel(
            name="CODE",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=100)),
            ],
        ),
    ]
