# Generated by Django 4.1 on 2024-06-07 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="code",
            name="code",
            field=models.TextField(),
        ),
    ]
